export enum Genero {
    MASCULINO = "MASCULINO",
    FEMININO = "FEMININO",
    OUTRO = "OUTRO",
  }
  
  export enum Formacao {
    ENSINO_FUNDAMENTAL = "ENSINO_FUNDAMENTAL",
    ENSINO_MEDIO = "ENSINO_MEDIO",
    GRADUACAO = "GRADUACAO",
    MESTRADO = "MESTRADO",
    DOUTORADO = "DOUTORADO",
    POS_DOUTORADO = "POS_DOUTORADO",
  }
  
  export enum Cargo {
    PROPRIETARIO = "PROPRIETARIO",
    GERENTE = "GERENTE",
    AGRONOMO_RESIDENTE = "AGRONOMO_RESIDENTE",
    AGRONOMO_CONSULTOR = "AGRONOMO_CONSULTOR",
    SUPERVISOR_DE_AREA = "SUPERVISOR_DE_AREA",
    SECRETARIO = "SECRETARIO",
  }